version: "3"

services:
  proxy:
    image: nginx
    #    build: ./datanode_nginx
    restart: always
    container_name: nginx_proxy
    volumes:
      - ./data/nginx/conf:/etc/nginx/conf.d
    ports:
      - 8090:8090
    networks:
      hadoopnet:
        ipv4_address: 172.28.0.2
  namenode:
    hostname: namenode
    build: ./namenode
#    image: fhamster/hadoop-namenode:hadoop3.2.1-java8-0.1
#    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
#    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - ./data/swap:/swap
    environment:
      - CLUSTER_NAME=HadoopCluster
    env_file:
      - ./hadoop.env
    networks:
      hadoopnet:
        ipv4_address: 172.28.0.3
  datanode1:
    hostname: datanode1
#    build: ./datanode
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    restart: always
    depends_on:
      - namenode
    volumes:
      - ./data/datanode1:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    networks:
      hadoopnet:
        ipv4_address: 172.28.0.4

  datanode2:
    hostname: datanode2
#    build: ./datanode
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    restart: always
    depends_on:
      - namenode
    volumes:
      - ./data/datanode2:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    networks:
      hadoopnet:
        ipv4_address: 172.28.0.5

  datanode3:
    hostname: datanode3
#    build: ./datanode
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode3
    restart: always
    depends_on:
      - namenode
    volumes:
      - ./data/datanode3:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    networks:
      hadoopnet:
        ipv4_address: 172.28.0.6

  resourcemanager:
    hostname: resourcemanager
#    build: ./resourcemanager
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    restart: always
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3
    ports:
    - 8088:8088
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode1:9864 datanode2:9864 datanode3:9864"
    env_file:
      - ./hadoop.env
    networks:
      hadoopnet:
        ipv4_address: 172.28.0.7

  nodemanager:
    hostname: nodemanager
#    build: ./nodemanager
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager
    restart: always
    ports:
    - 8042:8042
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3
      - resourcemanager
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode1:9864 datanode2:9864 datanode3:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    networks:
      hadoopnet:
        ipv4_address: 172.28.0.8
  historyserver:
    hostname: historyserver
#    build: ./historyserver
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: historyserver
    restart: always
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3
    ports:
    - 8188:8188
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode1:9864 datanode2:9864 datanode3:9864 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
    networks:
      hadoopnet:
        ipv4_address: 172.28.0.9
volumes:
  hadoop_namenode:
#  hadoop_datanode:
  hadoop_historyserver:

networks:
  hadoopnet:
    driver: "bridge"
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24
#          gateway: 172.28.0.1