version: "3"

services:
  proxy:
    image: nginx
    restart: always
    container_name: nginx_proxy
    volumes:
      - ./data/nginx/conf:/etc/nginx/conf.d
    ports:
      - 8090:8090
    networks:
      hadoopnet:
        ipv4_address: 172.28.0.2

  namenode:
    hostname: namenode
#    build: ./namenode/namenode_spark
    image: fhamster/hadoop-namenode:hadoop3.2.1-java8-0.1
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - ./data/swap:/swap
    environment:
      - CLUSTER_NAME=HadoopCluster
    env_file:
      - ./hadoop.env
    networks:
      hadoopnet:
        ipv4_address: 172.28.0.3
  datanode1:
    hostname: datanode1
    image: fhamster/hadoop-datanode:hadoop3.2.1-java8-0.1
    container_name: datanode1
    restart: always
    depends_on:
      - namenode
    volumes:
      - ./data/datanode1:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    networks:
      hadoopnet:
        ipv4_address: 172.28.0.4

  datanode2:
    hostname: datanode2
    image: fhamster/hadoop-datanode:hadoop3.2.1-java8-0.1
    container_name: datanode2
    restart: always
    depends_on:
      - namenode
    volumes:
      - ./data/datanode2:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    networks:
      hadoopnet:
        ipv4_address: 172.28.0.5

  datanode3:
    hostname: datanode3
    image: fhamster/hadoop-datanode:hadoop3.2.1-java8-0.1
    container_name: datanode3
    restart: always
    depends_on:
      - namenode
    volumes:
      - ./data/datanode3:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    networks:
      hadoopnet:
        ipv4_address: 172.28.0.6

volumes:
  hadoop_namenode:
#  hadoop_datanode:
  hadoop_historyserver:

networks:
  hadoopnet:
    driver: "bridge"
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24
#          gateway: 172.28.0.1